name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'build/build.zip'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Unzip build
        run: unzip build/build.zip -d site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/build/web/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
